### ISSUE TITLE
Compilation failing on ZCU104 on top PYNQ

### ISSUE THREAD

**Issue by abdulazizm** [Xilinx/pyxir#32]
trying to build master/default branch Pyxir with DPU-PYNQ (2.6 SD card image) for TVM workflow.

Cant able to build :  using `sudo python3 setup.py install --use_vai_rt_dpuczdx8g` command
but -> `sudo python3 setup.py install` this command builds but guess both are not same. Any suggestions?

`In file included from /root/vai_1.3_tvm/tvm/pyxir/src/pyxir/runtime/backends/vai_rt/vai_api/dpu_func.cpp:23:
/root/vai_1.3_tvm/tvm/pyxir/src/pyxir/runtime/backends/vai_rt/vai_api/dpu_func.hpp:20:10: fatal error: dpu_runner.hpp: No such file or directory
   20 | #include <dpu_runner.hpp>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/pyxir.dir/build.make:326: recipe for target 'CMakeFiles/pyxir.dir/src/pyxir/runtime/backends/vai_rt/vai_api/dpu_func.cpp.o' failed
make[2]: *** [CMakeFiles/pyxir.dir/src/pyxir/runtime/backends/vai_rt/vai_api/dpu_func.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pyxir.dir/all' failed
make[1]: *** [CMakeFiles/pyxir.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 291, in <module>
    zip_safe=False
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 24, in run
    self.build()
  File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 161, in run
    self.build_extension(ext)
  File "setup.py", line 206, in build_extension
    cwd=self.build_temp)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.`

**Comment by jtuyls** [comment]
@abdulazizm Did you clone and install pynq-dpu version 1.2.0 (https://tvm.apache.org/docs/deploy/vitis_ai.html#edge-hardware-setup)? The latest version of pynq-dpu switches the Vitis AI runtime from DNNDK to VART and we will update the TVM flow for that shortly, but for now we specifically need pynq-dpu version 1.2.0. If installed correctly, the dpu_runner.hpp should be located in /usr/include/vai.

**Comment by abdulazizm** [comment]
I used master branch from [https://github.com/Xilinx/DPU-PYNQ](DPU-PYNQ) (That may be the reason I am not getting `dexplorer - command not found error`). Now it makes more sense.

1. Is there any compatibility matrix for tvm workflow? I am very much confused with versions of PYXIR, DPU-PYNQ, TVM
2. I am in need to use tvm's master branch (as it has more new api's for me to compile/annotate deeplab v3 model from pytorch). Can I use TVM's master branch with pynq-dpu version 1.2.0?

Thanks for the reply!!

**Comment by jtuyls** [comment]
@abdulazizm Yes, the instructions previously pointed to dpu-pynq master (as that was v0.1.2) but we fixed it now because of the dpu-pynq change. I recommend looking at this page for the latest instructions: https://tvm.apache.org/docs/deploy/vitis_ai.html#edge-hardware-setup.

1. Latest TVM and PyXIR work with DPU-Pynq V0.1.2. We always verify latest TVM with latest PyXIR so that should keep working. We should have fixed the DPU-PYNQ version in the instructions to avoid these compatibility issues.
2. Yes.
3. Yes, the latest TVM Vitis AI instructions (https://tvm.apache.org/docs/deploy/vitis_ai.html#edge-hardware-setup) are using Pynq v2.6.

**Comment by abdulazizm** [comment]
@jtuyls Thanks!

I just followed the steps as mentioned here - [Vitis-AI Integration — tvm 0.8.dev0 documentation](https://tvm.apache.org/docs/deploy/vitis_ai.html#edge-hardware-setup)
Throws this error while importing relay:

```
root@pynq:/home/xilinx/tvm/python# python3 -c 'from tvm import relay'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xilinx/tvm/python/tvm/relay/__init__.py", line 23, in <module>
from . import ty
  File "/home/xilinx/tvm/python/tvm/relay/ty.py", line 26, in <module>
Any = _ffi_api.Any
AttributeError: module 'tvm.relay._ffi_api' has no attribute 'Any'
```

Tried with TVM v0.7.0 branch too. Pops the same error. (Please refer: https://discuss.tvm.apache.org/t/attributeerror-when-import-tvm-relay/3305/6)

Then I noticed that “Any” variable is not used anywhere in the file (other than this creating/assigning instance) - /home/xilinx/tvm/python/tvm/relay/ty.py - Commented this line and tried to do “python3 -c ‘from tvm import relay’” but throws another error:

```
root@pynq:/home/xilinx/tvm/python# python3 -c 'from tvm import relay'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xilinx/tvm/python/tvm/relay/__init__.py", line 29, in <module>
    from . import prelude
  File "/home/xilinx/tvm/python/tvm/relay/prelude.py", line 20, in <module>
    from tvm.relay.transform import ToANormalFormExpr
  File "/home/xilinx/tvm/python/tvm/relay/transform/__init__.py", line 20, in <module>
    from .transform import *
  File "/home/xilinx/tvm/python/tvm/relay/transform/transform.py", line 944, in <module>
    @function_pass(opt_level=1)
  File "/home/xilinx/tvm/python/tvm/relay/transform/transform.py", line 932, in create_function_pass
    info = tvm.transform.PassInfo(opt_level, fname, required)
  File "/home/xilinx/tvm/python/tvm/ir/transform.py", line 49, in __init__
    self.__init_handle_by_constructor__(_ffi_transform_api.PassInfo, opt_level, name, required)
AttributeError: module 'tvm.ir._ffi_transform_api' has no attribute 'PassInfo'
```
Any suggestions?

**Comment by jtuyls** [comment]
@abdulazizm The instructions only build the TVM runtime and not the full TVM package to make it more lightweight and therefore relay is not available. However, you don't need relay to run a cross-compiled module on the board. See this file for an example script for running on an edge device: https://github.com/Xilinx/pyxir/blob/master/examples/tvm/edge_resnet_18_board.py.

**Comment by abdulazizm** [comment]
@jtuyls Thanks a lot. It clears a lot. 

I was facing an issue related to tvm.relay.op.contrib.vitis_ai.annotation API and opened issue [here](https://github.com/Xilinx/Vitis-AI/issues/321) a week ago. Do you have any suggestions for this?

**Comment by abdulazizm** [comment]
Opened a new issue for easy tracking (AssertionError while annotating deeplabv3 model from pytorch) -> https://github.com/Xilinx/pyxir/issues/33
